# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  schedule:
    - cron: '50 * * 12 *'
    - cron: '5,20,35 5-6 * 12 *'
  workflow_dispatch:

name: Build-Site

jobs:
  Build-Site:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # Use older ubuntu to maximise backward compatibility
          - {os: ubuntu-20.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AOC_COOKIE: ${{ secrets.AOC_COOKIE}}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Build Site
        run: |
          rmarkdown::render_site()
        shell: Rscript {0}

      - name: Commit Site
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m "Automated Leaderboard Update `date`" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
